package com.example.chaozhou.local.table;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.chaozhou.local.table.Hotel;
import com.example.chaozhou.local.table.User;

import com.example.chaozhou.local.table.HotelDao;
import com.example.chaozhou.local.table.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hotelDaoConfig;
    private final DaoConfig userDaoConfig;

    private final HotelDao hotelDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hotelDaoConfig = daoConfigMap.get(HotelDao.class).clone();
        hotelDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        hotelDao = new HotelDao(hotelDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Hotel.class, hotelDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        hotelDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public HotelDao getHotelDao() {
        return hotelDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
